export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const ADD = 'ADD'
export const SUBTRACT = 'SUBTRACT'
export const RESET = 'RESET'
export const SAVE = 'SAVE'
export const REMOVE = 'REMOVE'

export const LOGINMODAL = 'LOGINMODAL'
export const LOGOUTMODAL = 'LOGOUTMODAL'
export const SIGNUPMODAL = 'SIGNUPMODAL'
export const DELETEPROFILEMODAL = 'DELETEPROFILEMODAL'

export const SHOWMODAL = 'SHOWMODAL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REFRESH = 'AUTH_REFRESH'
export const AUTH_DELETE = 'AUTH_DELETE'
export const AUTH_TIMEOUT = 'AUTH_TIMEOUT'

export const LOGIN_USER = 'LOGIN_USER'
export const SIGNUP_USER = 'SIGNUP_USER'

export const STORE_USER_INFO = 'STORE_USER_INFO'
export const STORE_USER_QUESTIONS = 'STORE_USER_QUESTIONS'

export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'
export const CLEAR_USER_QUESTIONS = 'CLEAR_USER_QUESTIONS'

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'

export const DELETE_USER = 'DELETE_USER'

export const GET_QUESTION_TOTALS = 'GET_QUESTION_TOTALS'
export const STORE_QUESTION_TOTALS = 'STORE_QUESTION_TOTALS'

export const GET_QUICK_QUESTION = 'GET_QUICK_QUESTION'

export const SET_GAME_MODE = 'SET_GAME_MODE'
export const RESET_GAME_MODE = 'RESET_GAME_MODE'
