export const LOADINGMODAL = 'LOADINGMODAL'
export const LOGINMODAL = 'LOGINMODAL'
export const LOGOUTMODAL = 'LOGOUTMODAL'
export const SIGNUPMODAL = 'SIGNUPMODAL'
export const DELETEPROFILEMODAL = 'DELETEPROFILEMODAL'
export const SHOWMODAL = 'SHOWMODAL'

export const AUTH_UPDATE_LOADING_STATUS = 'AUTH_UPDATE_LOADING_STATUS'
export const AUTH_UPDATE_STATUS = 'AUTH_UPDATE_STATUS'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_SIGNUP = 'AUTH_SIGNUP'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REFRESH = 'AUTH_REFRESH'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_CERT = 'AUTH_CERT'
export const AUTH_VALID = 'AUTH_VALID'
export const AUTH_DELETE = 'AUTH_DELETE'
export const AUTH_TIMEOUT = 'AUTH_TIMEOUT'
export const AUTH_CLEAR_STATE = 'AUTH_CLEAR_STATE'
export const CLEAR_AUTH_CREDS = 'CLEAR_AUTH_CREDS'
export const CLEAR_AUTH_TYPE = 'CLEAR_AUTH_TYPE'
export const CLEAR_AUTH_STATUS = 'CLEAR_AUTH_STATUS'
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS'
export const SET_AUTH_TYPE = 'SET_AUTH_TYPE'

export const STORE_USER_INFO = 'STORE_USER_INFO'
export const STORE_USER_QUESTIONS = 'STORE_USER_QUESTIONS'

export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'
export const CLEAR_USER_QUESTIONS = 'CLEAR_USER_QUESTIONS'

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_QUESTIONS = 'UPDATE_USER_QUESTIONS'
export const UPDATE_USER_PERFORMANCE_FROM_PLAY_CONTROLLER = 'UPDATE_USER_PERFORMANCE_FROM_PLAY_CONTROLLER'
export const UPDATE_USER_EXPERIENCE_FROM_PLAY_CONTROLLER = 'UPDATE_USER_EXPERIENCE_FROM_PLAY_CONTROLLER'
export const UPDATE_USER_QUESTIONIDS_FROM_PLAY_CONTROLLER = 'UPDATE_USER_QUESTIONIDS_FROM_PLAY_CONTROLLER'
export const UPDATE_USER_QUESTIONS_FROM_PLAY_CONTROLLER = 'UPDATE_USER_QUESTIONS_FROM_PLAY_CONTROLLER'
export const UPDATE_USER_QUESTION_TOTALS_FROM_PLAY_CONTROLLER = 'UPDATE_USER_QUESTION_TOTALS_FROM_PLAY_CONTROLLER'

export const DELETE_USER = 'DELETE_USER'

export const GET_QUESTION_TOTALS = 'GET_QUESTION_TOTALS'
export const STORE_QUESTION_TOTALS = 'STORE_QUESTION_TOTALS'
export const CLEAR_QUESTION_TOTALS = 'CLEAR_QUESTION_TOTALS'

export const UPDATE_QUESTION_TOTALS_FROM_PLAY_CONTROLLER = 'UPDATE_QUESTION_TOTALS_FROM_PLAY_CONTROLLER'
export const UPDATE_USER_VOTES_FROM_PLAY_CONTROLLER = 'UPDATE_USER_VOTES_FROM_PLAY_CONTROLLER'
export const UPDATE_USER_COMMENTS_FROM_PLAY_CONTROLLER = 'UPDATE_USER_COMMENTS_FROM_PLAY_CONTROLLER'

export const GET_QUICK_QUESTION = 'GET_QUICK_QUESTION'
export const GET_DIFF_QUESTION = 'GET_DIFF_QUESTION'
export const GET_CAT_QUESTION = 'GET_CAT_QUESTION'

export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS'
export const UPDATE_VOTE_STATUS = 'UPDATE_VOTE_STATUS'
export const UPDATE_COMMENT_STATUS = 'UPDATE_COMMENT_STATUS'

export const SET_GAME_MODE = 'SET_GAME_MODE'
export const RESET_GAME_MODE = 'RESET_GAME_MODE'

export const SET_GAME_STATE = 'SET_GAME_STATE'
export const RESET_GAME_STATE = 'RESET_GAME_STATE'

export const SET_GAME_QSET = 'SET_GAME_QSET'
export const RESET_GAME_QSET = 'RESET_GAME_QSET'

export const SET_QUESTION = 'SET_QUESTION'
export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const RESET_QUESTION = 'RESET_QUESTION'

export const SET_ANSWER = 'SET_ANSWER'
export const RESET_ANSWER = 'RESET_ANSWER'

export const GET_RESULTS = 'GET_RESULTS'
export const SET_RESULTS = 'SET_RESULTS'
export const RESET_RESULTS = 'RESET_RESULTS'

export const SET_VOTE = 'SET_VOTE'
export const RESET_VOTE = 'RESET_VOTE'

export const SET_COMMENT = 'SET_COMMENT'
export const RESET_COMMENT = 'RESET_COMMENT'
export const EDIT_USER_COMMENT = 'EDIT_USER_COMMENT'
export const DELETE_USER_COMMENT = 'DELETE_USER_COMMENT'
export const DELETE_QUESTION_COMMENT = 'DELETE_QUESTION_COMMENT'
export const EDIT_QUESTION_COMMENT = 'EDIT_QUESTION_COMMENT'

export const STORE_ACHIEVEMENTS = 'STORE_ACHIEVEMENTS'
export const CLEAR_ACHIEVEMENTS = 'CLEAR_ACHIEVEMENTS'

